# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Kyle Wong's Blog
description:      'A coder wanna to make a difference.Connect me by <a href="http://weibo.com/kangwang1988" target="_blank">@KyleWong</a>.'
url:              https://github.com/kangwang1988/kangwang1988.github.io
baseurl:          /

author:
  name:           'Kyle Wong'
  url:            http://kangwang1988.github.io/

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/kangwang1988/kangwang1988.github.io
